---
- name: 2.1 Restrict network traffic between containers (Scored)
  shell: ps -ef | grep '[i]cc=false'
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.1

- name: 2.2 Set the logging level (Scored)
  shell: ps -ef | grep '[l]og-level=info'
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.2

- name: 2.3 Allow Docker to make changes to iptables (Scored)
  shell: ps -ef | grep '[i]ptables=true'
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.3

- name: 2.4 Do not use insecure registries (Scored)
  shell: ps -ef | grep '[i]nsecure-registry'
  register: res
  failed_when: res.rc == 0
  changed_when: res.rc == 0
  always_run: yes
  tags:
   - scored
   - section2.4

- name: 2.5 Do not use the aufs storage driver (Scored)
  debug: msg=" docker info | grep -e '^Storage Driver:\s*aufs\s*$' shold return nothing"
  tags:
   - scored
   - section2.5

- name: 2.6 Configure TLS authentication for Docker daemon (Scored)
  debug: msg="Manual action needed"
  tags:
   - scored
   - section2.6

- name: 2.7 Set default ulimit as appropriate (Not Scored)
  shell: ulimit -n 90000
  tags:
   - notscored
   - section2.7

