---
- name: 1.1 Create a separate partition for containers (Scored)
  command: "grep /var/lib/docker fstab"
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section1.1

- name: Fail when file does not exist
  fail: msg="fstab No such file or directory"
  when: "'grep: fstab: No such file or directory' in res.stderr"
  tags:
   - scored
   - section1.1

- name: 1.2 Use the updated Linux Kernel (Scored)
  shell: uname -r | grep ^3\.10
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section1.2

- name: 1.3 Harden the container host (Not Scored)
  debug: msg="*** This should be done by a separate playbook"
  tags:
   - notscored
   - section1.3

- name: 1.4 Remove all non-essential services from the host (Not Scored)
  debug: msg="*** Not in a scope of this playbook"
  tags:
   - notscored
   - section1.4

- name: 1.5 Keep Docker up to date (Not Scored)
  debug: msg="*** Not in a scope of this playbook"
  tags:
   - notscored
   - section1.5

- name: 1.6 Only allow trusted users to control Docker daemon (Scored)
  debug: msg="*** Not in a scope of this playbook"
  tags:
   - scored
   - section1.6

- name: 1.7 - 1.15 Configure auditd Rules (Scored)
  copy: >
      src=audit.rules
      dest=/etc/audit/audit.rules
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.7
   - section1.8
   - section1.9
   - section1.10
   - section1.11
   - section1.12
   - section1.13
   - section1.14
   - section1.15

